os: osx
osx_image: xcode11.3

branches:
  only:
  - master

language: ruby

env:
  HOMEBREW_NO_INSTALL_CLEANUP=1
  HOMEBREW_NO_AUTO_UPDATE=1
  PYTHON_VERSION=3.8.1

cache:
  bundler: true
  pip: true
  directories:
    - $HOME/.rvm
    - $HOME/Library/Caches/Homebrew # https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci
    - /usr/local/Homebrew
    - $HOME/.cache/pip
    - $HOME/.cache/pyenv

rvm:
  - '2.7.0'

before_install:
  - gem install bundler
  - gem install rubocop
  - brew install macvim

install:
  - |
    which pyenv
    whereis pyenv
    eval "$(pyenv init -)"
    pyenv install --skip-existing "$PYTHON_VERSION"
    pyenv global "$PYTHON_VERSION"
    pyenv shell "$PYTHON_VERSION"
    pyenv local "$PYTHON_VERSION"
    pyenv rehash
    pip3 --version
    pip3 install vim-vint

    bundle install


script:
  - vint -s --enable-neovim plugin/*.vim
  - rubocop
  - bundle exec rspec --format documentation
