#!/bin/sh
# <https://github.com/zmughal/vimrc>
# git clone git@github.com:zmughal/vimrc.git

CURDIR=`dirname "$0"`
cd "$CURDIR"
CUR="`pwd -P`"
ln -sf "$CUR/.vim"           "$HOME"
ln -sf "$CUR/.vimlocal"      "$HOME"
#ln -sf "$CUR/.vimoutliner"   "$HOME"
ln -sf "$CUR/.gvimrc"        "$HOME"
#ln -sf "$CUR/.vimoutlinerrc" "$HOME"
ln -sf "$CUR/.vimrc"         "$HOME"
mkdir "$HOME/bin" 2>/dev/null
ln -sf -t "$HOME/bin" "$HOME/.vim/scripts/pipe.vim"
