#!/bin/bash

COMMIT_FILE="COMMIT"

refresh_git() {
  local url="$1"
  local dir="$2"
  local branch="$3"

  rm -rf $dir
  if [ -z "$branch" ]; then
    branch="master"
  fi
  BRANCH="--branch=$branch"
  echo "$BRANCH"
  git clone $url $dir "$BRANCH" --depth=1
  COMMIT=$(git --git-dir=$dir/.git log | head -1 | sed 's,^commit ,,')
  #echo -e "$url\t$COMMIT" >> $COMMIT_FILE
  rm -rf $dir/.git

  if [ -f "$dir/.gitignore" ]; then
    rm "$dir/.gitignore"
  fi

  STATUS=$(git status --porcelain | grep ".vim/bundle/$dir" )
  if [ ! -z "$STATUS" ]; then
    git add $dir
    git commit -m "refresh bundles [automated]: $url @ $COMMIT"
  fi
}

STAGED=$( git diff --cached )
if [ ! -z "$STAGED" ]; then
  echo "Can't have staged changes"
  exit;
fi

#rm -f $COMMIT_FILE
refresh_git https://github.com/kchmck/vim-coffee-script.git vim-coffee-script
refresh_git https://github.com/scrooloose/syntastic.git syntastic
refresh_git https://github.com/mileszs/ack.vim.git ack.vim
refresh_git https://github.com/zmughal/vim-matlab-fold vim-matlab-fold zmughal
refresh_git https://github.com/wesQ3/vim-windowswap vim-windowswap
refresh_git https://github.com/ervandew/supertab supertab
refresh_git https://github.com/luochen1990/rainbow rainbow-paren-improved
refresh_git https://github.com/zeis/vim-kolor colorscheme-kolor
refresh_git https://github.com/chrisbra/Recover.vim.git recover.vim-swap
refresh_git https://github.com/airblade/vim-gitgutter vim-gitgutter
refresh_git https://github.com/Shougo/unite.vim unite.vim
refresh_git https://github.com/Shougo/neomru.vim neomru.vim
refresh_git https://github.com/Shougo/vimproc.vim vimproc.vim
#refresh https://bitbucket.org/ns9tks/vim-fuzzyfinder vim-fuzzyfinder
refresh_git https://github.com/terryma/vim-multiple-cursors vim-multiple-cursors

refresh_git https://github.com/ctrlpvim/ctrlp.vim ctrlp.vim
refresh_git https://github.com/DavidEGx/ctrlp-smarttabs ctrlp-smarttabs

refresh_git https://github.com/Shougo/neocomplete.vim neocomplete.vim
refresh_git https://github.com/mjbrownie/swapit swapit
refresh_git https://github.com/tpope/vim-abolish vim-abolish
refresh_git https://github.com/mattboehm/vim-unstack vim-unstack
refresh_git https://github.com/hari-rangarajan/CCTree CCTree

refresh_git https://github.com/jeetsukumaran/vim-indentwise vim-indentwise

refresh_git https://github.com/tpope/vim-fugitive vim-fugitive

refresh_git https://github.com/terryma/vim-expand-region vim-expand-region

refresh_git https://github.com/godlygeek/csapprox CSApprox

refresh_git https://github.com/vim-perl/vim-perl vim-perl-src
mkdir vim-perl;
make -Cvim-perl-src clean carp dancer highlight-all-pragmas moose test-more try-tiny
rsync -avz vim-perl-src/after vim-perl/
rm -Rfv vim-perl-src/after
git add vim-perl && git commit -m "refresh bundles [automated]: vim-perl built from vim-perl-src"

refresh_git https://github.com/dpelle/vim-LanguageTool vim-languagetool
refresh_git https://github.com/tpope/vim-dispatch vim-dispatch

refresh_git https://github.com/matze/vim-tex-fold vim-tex-fold

refresh_git https://github.com/LucHermitte/lh-vim-lib lh-vim-lib
refresh_git https://github.com/LucHermitte/local_vimrc local_vimrc

refresh_git https://github.com/tpope/vim-projectionist vim-projectionist

refresh_git https://github.com/easymotion/vim-easymotion vim-easymotion

refresh_git https://github.com/altercation/vim-colors-solarized vim-colors-solarized

refresh_git https://github.com/c9s/perlomni.vim perlomni.vim
refresh_git https://github.com/c9s/cpan.vim cpan.vim

refresh_git https://github.com/jeetsukumaran/vim-buffergator vim-buffergator
refresh_git https://github.com/tpope/vim-vinegar vim-vinegar
refresh_git https://github.com/jamessan/vim-gnupg vim-gnupg

refresh_git https://github.com/LucHermitte/lh-tags lh-tags
refresh_git https://github.com/LucHermitte/lh-dev lh-dev
refresh_git https://github.com/LucHermitte/lh-brackets lh-brackets
refresh_git https://github.com/LucHermitte/searchInRuntime searchInRuntime
refresh_git https://github.com/LucHermitte/mu-template mu-template
refresh_git https://github.com/tomtom/stakeholders_vim stakeholders_vim
refresh_git https://github.com/DataWraith/auto_mkdir auto_mkdir
refresh_git https://github.com/aklt/plantuml-syntax plantuml-syntax
