#!/bin/bash

COMMIT_FILE="COMMIT"

refresh() {
  local url="$1"
  local dir="$2"

  rm -rf $dir
  git clone $url $dir --depth=1
  COMMIT=$(git --git-dir=$dir/.git log | head -1 | sed 's,^commit ,,')
  #echo -e "$url\t$COMMIT" >> $COMMIT_FILE
  rm -rf $dir/.git

  if [ -f "$dir/.gitignore" ]; then
    rm "$dir/.gitignore"
  fi

  STATUS=$(git status --porcelain | grep ".vim/bundle/$dir" )
  if [ ! -z "$STATUS" ]; then
	  git add $dir
	  git commit -m "refresh bundles [automated]: $url @ $COMMIT"
  fi
}

STAGED=$( git diff --cached )
if [ ! -z "$STAGED" ]; then
	echo "Can't have staged changes"
	exit;
fi

#rm -f $COMMIT_FILE
refresh https://github.com/kchmck/vim-coffee-script.git vim-coffee-script
refresh https://github.com/scrooloose/syntastic.git syntastic
refresh https://github.com/mileszs/ack.vim.git ack.vim
