let g:alternateExtensions_CXX = "HXX,hxx,H,h"
let g:alternateExtensions_HXX = "CXX,cxx"
let g:alternateExtensions_cxx = "hxx,HXX,h,H"
let g:alternateExtensions_hxx = "cxx,CXX"
let g:alternateExtensions_h = "c,C,cxx,CXX,txx,TXX"
let g:alternateExtensions_txx = "hxx,HXX,h,H"
let g:alternateExtensions_TXX = "HXX,hxx,H,h"
